export enum Colors {
	PRIMARY = 'primary',
	PRIMARY_CONTENT = 'primary-content',
	ACCENT = 'accent',
	ACCENT_CONTENT = 'accent-content',
	SECONDARY = 'secondary',
	SECONDARY_CONTENT = 'secondary-content',
	NEUTRAL = 'neutral',
	NEUTRAL_CONTENT = 'neutral-content',
	BASE_100 = 'base-100',
	BASE_200 = 'base-200',
	BASE_300 = 'base-300',
	BASE_CONTENT = 'base-content',
	INFO = 'info',
	SUCCESS = 'success',
	WARNING = 'warning',
	ERROR = 'error',
	INFO_CONTENT = 'info-content',
	SUCCESS_CONTENT = 'success-content',
	WARNING_CONTENT = 'warning-content',
	ERROR_CONTENT = 'error-content',
}
