export enum ContainerGap {
	LG = 'gap-12',
	MD = 'gap-8',
	NONE = 'gap-0',
	SM = 'gap-6',
	X_LG = 'gap-x-12',
	X_MD = 'gap-x-8',
	X_SM = 'gap-x-6',
	X_XL = 'gap-x-16',
	X_XS = 'gap-x-4',
	XL = 'gap-16',
	XS = 'gap-4',
	XXS = 'gap-2',
	Y_LG = 'gap-y-12',
	Y_MD = 'gap-y-8',
	Y_SM = 'gap-y-6',
	Y_XL = 'gap-y-16',
	Y_XS = 'gap-y-4',
}
